const countries = [
  { name: 'España', code: 'ES', area: 'Europe' },
  { name: 'Francia', code: 'FR', area: 'Europe' },
  { name: 'Alemania', code: 'DE', area: 'Europe' },
  { name: 'Italia', code: 'IT', area: 'Europe' },
  { name: 'Reino Unido', code: 'GB', area: 'Europe' },
  { name: 'Países Bajos', code: 'NL', area: 'Europe' },
  { name: 'Suiza', code: 'CH', area: 'Europe' },
  { name: 'Austria', code: 'AT', area: 'Europe' },
  { name: 'Bélgica', code: 'BE', area: 'Europe' },
  { name: 'Portugal', code: 'PT', area: 'Europe' },
  { name: 'Suecia', code: 'SE', area: 'Europe' },
  { name: 'Noruega', code: 'NO', area: 'Europe' },
  { name: 'Estados Unidos', code: 'US', area: 'America' },
  { name: 'Canadá', code: 'CA', area: 'America' },
  { name: 'México', code: 'MX', area: 'America' },
  { name: 'Brasil', code: 'BR', area: 'America' },
  { name: 'Argentina', code: 'AR', area: 'America' },
  { name: 'Colombia', code: 'CO', area: 'America' },
  { name: 'Chile', code: 'CL', area: 'America' },
  { name: 'Perú', code: 'PE', area: 'America' },
  { name: 'Venezuela', code: 'VE', area: 'America' },
  { name: 'Ecuador', code: 'EC', area: 'America' },
  { name: 'Costa Rica', code: 'CR', area: 'America' },
  { name: 'Panamá', code: 'PA', area: 'America' },
  { name: 'Mongolia', code: 'MN', area: 'Asia' },
  { name: 'China', code: 'CN', area: 'Asia' },
  { name: 'Kazajistán', code: 'KZ', area: 'Asia' },
  { name: 'Ucrania', code: 'UA', area: 'Europe' },
  { name: 'Bielorrusia', code: 'BY', area: 'Europe' },
  { name: 'Finlandia', code: 'FI', area: 'Europe' },
  { name: 'Estonia', code: 'EE', area: 'Europe' },
  { name: 'Irán', code: 'IR', area: 'Asia' },
  { name: 'Turquía', code: 'TR', area: 'Asia' },
  { name: 'Jordania', code: 'JO', area: 'Asia' },
  { name: 'Kuwait', code: 'KW', area: 'Asia' },
  { name: 'Arabia Saudita', code: 'SA', area: 'Asia' },
  { name: 'Siria', code: 'SY', area: 'Asia' },
  { name: 'Líbano', code: 'LB', area: 'Asia' },
  { name: 'Israel', code: 'IL', area: 'Asia' },
  { name: 'Jordania', code: 'JO', area: 'Asia' },
  { name: 'Arabia Saudita', code: 'SA', area: 'Asia' },
  { name: 'Sudán', code: 'SD', area: 'Africa' },
  { name: 'Libia', code: 'LY', area: 'Africa' },
];

export { countries };
