let time_place = [
  { country: 'ES', place: 'madrid', area: 'Europe' },
  { country: 'FR', place: 'paris', area: 'Europe' },
  { country: 'DE', place: 'berlin', area: 'Europe' },
  { country: 'IT', place: 'rome', area: 'Europe' },
  { country: 'GB', place: 'london', area: 'Europe' },
  { country: 'NL', place: 'amsterdam', area: 'Europe' },
  { country: 'CH', place: 'zurich', area: 'Europe' },
  { country: 'AT', place: 'vienna', area: 'Europe' },
  { country: 'BE', place: 'brussels', area: 'Europe' },
  { country: 'PT', place: 'lisbon', area: 'Europe' },
  { country: 'SE', place: 'stockholm', area: 'Europe' },
  { country: 'NO', place: 'oslo', area: 'Europe' },
  { country: 'US', place: 'new_york', area: 'America' },
  { country: 'CA', place: 'toronto', area: 'America' },
  { country: 'MX', place: 'mexico_city', area: 'America' },
  { country: 'BR', place: 'rio_de_janeiro', area: 'America' },
  { country: 'AR', place: 'buenos_aires', area: 'America' },
  { country: 'CO', place: 'bogota', area: 'America' },
  { country: 'CL', place: 'santiago', area: 'America' },
  { country: 'PE', place: 'lima', area: 'America' },
  { country: 'VE', place: 'caracas', area: 'America' },
  { country: 'EC', place: 'quito', area: 'America' },
  { country: 'CR', place: 'san_jose', area: 'America' },
  { country: 'PA', place: 'panama_city', area: 'America' },
  { country: 'MN', place: 'ulaanbaatar', area: 'Asia' },
  { country: 'CN', place: 'shanghai', area: 'Asia' },
  { country: 'KZ', place: 'almaty', area: 'Asia' },
  { country: 'UA', place: 'kyiv', area: 'Europe' },
  { country: 'BY', place: 'minsk', area: 'Europe' },
  { country: 'FI', place: 'helsinki', area: 'Europe' },
  { country: 'EE', place: 'tallinn', area: 'Europe' },
  { country: 'IR', place: 'tehran', area: 'Asia' },
  { country: 'TR', place: 'istanbul', area: 'Asia' },
  { country: 'JO', place: 'amman', area: 'Asia' },
  { country: 'KW', place: 'kuwait_city', area: 'Asia' },
  { country: 'SA', place: 'riyadh', area: 'Asia' },
  { country: 'SY', place: 'damascus', area: 'Asia' },
  { country: 'LB', place: 'beirut', area: 'Asia' },
  { country: 'IL', place: 'jerusalem', area: 'Asia' },
  { country: 'SD', place: 'khartoum', area: 'Africa' },
  { country: 'LY', place: 'tripoli', area: 'Africa' },
];

export { time_place };
